<?php
    $db_handle = new DBController();
    $conn = $db_handle->connection();
    $query = 'SELECT * FROM `student_case` WHERE `id`='.$_GET['student'];
    $studentCases = $conn->query($query);
    //var_dump($studentCase);
    if (empty($_GET['student']) || ($studentCases->num_rows==0)):
        echo "<script>window.location='404';</script>";
    endif;
    $query = 'SELECT `id`,`name` FROM `document_types`';
    $documentTypes = $conn->query($query);

    $data = $studentCases->fetch_assoc();

    $query = 'SELECT `id`,`name` FROM `franchise` WHERE `id`='.$data['franchise'];
    $franchise = $conn->query($query);
    $franchise = $franchise->fetch_assoc();

    $query = 'SELECT `id`,`name` FROM `users` WHERE `id`='.$data['case_generated_by'];
    $caseGenerated = $conn->query($query);
    $caseGenerated= $caseGenerated->fetch_assoc();

    $query = 'SELECT * FROM `student_documents` WHERE `case_id`='.$data['id'];
    $student_documents = $conn->query($query);
    $check_documents= ($student_documents->num_rows>0)?"Documents":NULL;

    $query = 'SELECT * FROM `university_documents` WHERE `case_id`='.$data['id'];
    $university_documents = $conn->query($query);
    $check_documents_university= ($student_documents->num_rows>0)?"Documents":NULL;

    $query = 'SELECT * FROM `fee` WHERE `fees`="Consultancy" AND `case_id`='.$data['id'];
    $fee_consultancy = $conn->query($query);

    $query = 'SELECT * FROM `fee` WHERE `fees`="University" AND `case_id`='.$data['id'];
    $fee_university = $conn->query($query);

    $checkFeeConsultancy= ($fee_consultancy->num_rows>0)?"Fee":NULL;
    $checkFeeUniversity= ($fee_university->num_rows>0)?"Fee":NULL;
    ?>
<div class="row" >
    <div class="col-md-12">
        <div class="text-left" style="float:left;">
            <a href="javascript:history.back()" class="btn btn-info btn-sm"><i class="fas fa-arrow-circle-left"></i></a>
        </div>
        <div class="text-right">
            <a class="btn btn-info" href="<?=$config['URL']?>/index?nav=student-cases">View All Cases</a>
        </div>
        <div class="clearfix"><br></div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title lead">Student: <?=$data['name'];?> | Basic Information</h1>
                <?php if ($logged_in_user_data["role_id"]!=4): ?>
                    <div class="text-right">
                        <a class="btn btn-info" href="<?=$config['URL']?>/index?nav=edit-student-case&student=<?=$data['id']?>">Edit Student Case</a>
                    </div>
                <?php endif; ?>
                <p><b>Name:</b> <?=$data['name']?></p>
                <p><b>Email:</b> <?=$data['email']?></p>
                <p><b>Phone:</b> <?=$data['phone']?></p>
                <p><b>Qualification:</b> <?=$data['qualification']?></p>
                <p><b>CNIC:</b> <?=$data['cnic']?></p>
                <p><b>Passport:</b> <?=$data['passport']?></p>
                <p><b>Preferred Courses:</b> <?=$data['courses']?></p>
                <p><b>Franchise:</b> <?=$franchise['name']?></p>
                <p><b>Case Generated By:</b> <?=$caseGenerated['name']?></p>
            </div>
        </div>
    </div>
</div>

<div class="row small-spacing">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title lead">Student: <?=$data['name'];?> | Documents</h1>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="text-right">
                            <a class="btn btn-info" href="<?=$config['URL']?>/index?nav=document-submission&document=student&student=<?=$data['id']?>">Add Student Documents</a>
                        </div>
                        <h4>Student Documents</h4>
                        <table class="table table-bordered table-stripped">
                            <thead>
                            <th>Id</th>
                            <th>Document</th>
                            <th>Action</th>
                            <th>Notes</th>
                            </thead>
                            <tbody>
                            <?php if ($check_documents!=NULL): $i=1; ?>
                                <?php while($d=$student_documents->fetch_assoc()): ?>
                                    <tr>
                                        <td><?=$i++;?></td>
                                        <?php if ($d['file']=="404"): ?>
                                            <td><a href="index?nav=404"><?=$d['name']?></a></td>
                                            <td><p><a class="btn btn-small btn-primary" href="<?=$config['URL']?>/index?nav=document-edit&documents=student&student=<?=$data['id']?>&document=<?=$d['id'];?>">Upload the Missing Document</a></p></td>
                                        <?php else: ?>
                                            <td><a href="uploads/<?=$d['file']?>"><?=$d['name']?></a></td>
                                            <td><p><a class="btn btn-small btn-info" href="<?=$config['URL']?>/index?nav=document-edit&documents=student&student=<?=$data['id']?>&document=<?=$d['id'];?>">Update the Document</a></p></td>
                                        <?php endif; ?>
                                        <td><p class="small"><?=$d['notes']?></p></td>
                                    </tr>
                                <?php
                                endwhile;
                            else:
                                echo "<tr>No Documents Found</tr>";
                            endif;
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-right">
                            <a class="btn btn-info" href="<?=$config['URL']?>/index?nav=document-submission&document=university&student=<?=$data['id']?>">Add University Documents</a>
                        </div>
                        <h4>University Documents</h4>
                        <table class="table table-bordered table-stripped">
                            <thead>
                            <th>Id</th>
                            <th>Document</th>
                            <th>Action</th>
                            <th>Notes</th>
                            </thead>
                            <tbody>
                            <?php if ($check_documents_university!=NULL): $i=1; ?>
                                <?php while($d=$university_documents->fetch_assoc()): ?>
                                    <tr>
                                        <td><?=$i++;?></td>
                                        <?php if ($d['file']=="404"): ?>
                                            <td><a href="index?nav=404"><?=$d['name']?></a></td>
                                            <td><p><a class="btn btn-small btn-warning" href="<?=$config['URL']?>/index?nav=document-edit&documents=university&student=<?=$data['id']?>&document=<?=$d['id'];?>">Upload the Missing Document</a></p></td>
                                        <?php else: ?>
                                            <td><a href="uploads/<?=$d['file']?>"><?=$d['name']?></a></td>
                                            <td><p><a class="btn btn-small btn-info" href="<?=$config['URL']?>/index?nav=document-edit&documents=university&student=<?=$data['id']?>&document=<?=$d['id'];?>">Update the Document</a></p></td>
                                        <?php endif; ?>
                                        <td><p class="small"><?=$d['notes']?></p></td>
                                    </tr>
                                <?php
                                endwhile;
                            else:
                                echo "<tr>No Documents Found</tr>";
                            endif;
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row small-spacing">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title lead">Student: <?=$data['name'];?> | Invoices</h1>
                <div class="text-right">
                    <a class="btn btn-info" href="<?=$config['URL']?>/index?nav=add-invoice&student=<?=$data['id']?>">Add Student Invoices</a>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <h4 class="text-center">Consultancy</h4>
                        <?php if ($checkFeeConsultancy!=NULL): $i=1;?>
                            <table class="table table-bordered table-stripped table-responsive">
                                <thead>
                                <th>#</th>
                                <th>Fee</th>
                                <th>Fee Amount</th>
                                <th>Fee Type</th>
                                <th>Notes</th>
                                <th></th>
                                </thead>
                                <tbody>
                                <?php while($d=$fee_consultancy->fetch_assoc()): ?>
                                    <tr>
                                        <td><?=$i++;?></td>
                                        <td><?=$d['fees'];?></td>
                                        <td><?=$d['fee_amount'];?></td>
                                        <td><?=$d['fee_type'];?></td>
                                        <td><p><?=$d['notes'];?></p></td>
                                        <td class="text-center"><a class="btn btn-primary" href="<?=$config['URL']?>/index?nav=invoice&student=<?=$data['id']?>&fee=<?=$d['id']?>">View Invoice</a></td>
                                    </tr>
                                <?php endwhile; ?>
                                </tbody>
                                <tfoot>
                                <th>#</th>
                                <th>Fee</th>
                                <th>Fee Amount</th>
                                <th>Fee Type</th>
                                <th>Notes</th>
                                <th></th>
                                </tfoot>
                            </table>
                        <?php else: ?>
                            <b>Fee Record Not Found</b>
                        <?php endif; ?>
                    </div>
                    <div class="col-lg-6">
                        <h4 class="text-center">University</h4>
                        <?php if ($checkFeeUniversity!=NULL): $i=1;?>
                            <table class="table table-bordered table-stripped table-responsive">
                                <thead>
                                <th>#</th>
                                <th>Fee</th>
                                <th>Fee Amount</th>
                                <th>Fee Type</th>
                                <th>Notes</th>
                                <th></th>
                                </thead>
                                <tbody>
                                <?php while($d=$fee_university->fetch_assoc()): ?>
                                    <tr>
                                        <td><?=$i++;?></td>
                                        <td><?=$d['fees'];?></td>
                                        <td><?=$d['fee_amount'];?></td>
                                        <td><?=$d['fee_type'];?></td>
                                        <td><p><?=$d['notes'];?></p></td>
                                        <td class="text-center"><a class="btn btn-primary" href="<?=$config['URL']?>/index?nav=invoice&student=<?=$data['id']?>&fee=<?=$d['id']?>">View Invoice</a></td>
                                    </tr>
                                <?php endwhile; ?>
                                </tbody>
                                <tfoot>
                                <th>#</th>
                                <th>Fee</th>
                                <th>Fee Amount</th>
                                <th>Fee Type</th>
                                <th>Notes</th>
                                <th></th>
                                </tfoot>
                            </table>
                        <?php else: ?>
                            <b>Fee Record Not Found</b>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
